version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api-server:
    build: ./server
    ports:
      - "8081:8081"
    environment:
      - SPRING_EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - SPRING_EUREKA_CLIENT_FETCH_REGISTRY=false
    depends_on:
      - mysql
      - rabbitmq

  api-gateway:
    build: ./gateway
    ports:
      - "8082:8082"
    depends_on:
      - api-server

  api-pedidos:
    build: ./pedidos
    ports:
      - "40001:40001"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/alurafood-pedidos
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://api-server:8081/eureka
    depends_on:
      - api-server
      - mysql
      - rabbitmq

  api-pagamento:
    build: ./pagamento
    ports:
      - "40000:40000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/alurafood-pagamento
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://api-server:8081/eureka
    depends_on:
      - api-server
      - mysql
      - rabbitmq

  api-avaliacao:
    build: ./avaliacao
    depends_on:
      - api-server
      - api-gateway        

volumes:
  mysql-data:
