name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - kubernetes  # Incluir aqui a branch que acionará o pipeline completo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    # Build a Docker image
    - name: Build Docker image
      run: |
        docker build -t my-app:latest .

    # Log in to DockerHub
    - name: Log in to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Tag and push the Docker image to DockerHub
    - name: Push Docker image to DockerHub
      run: |
        docker tag my-app:latest ${{ secrets.DOCKER_USERNAME }}/my-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

    # Test and Deploy to Kubernetes only on the 'kubernetes' branch
    - name: Deploy to Kubernetes
      if: github.ref == 'refs/heads/kubernetes'  # Condição para rodar apenas na branch 'kubernetes'
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl apply -f k8s/deployment.yml

